### ISSUE TITLE
Experiencing ArgumentNullException on login callback

### ISSUE THREAD

**Issue by chrsin** [ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect#10]
Hey, I'm pretty sure I have everything setup properly based on the guide in your readme file, but on the callback (after visiting the IDP) I'm getting the following error:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Failed to handle login call back, response URL 'https://localhost:4000/authentication/login_callback#state=HRdqLNnA6Eeap23YwiTqZt-RG41BfeeOTf-5cUKyeNA&session_state=f47d2784-6bc6-4e43-9976-6437dfb30b7c&code=5933f67d-201a-4871-b080-78d71610c34a.f47d2784-6bc6-4e43-9976-6437dfb30b7c.a09a64c7-48f7-4ec6-bc15-2fc79b498bff'.
System.Security.SecurityException: Failed to handle login call back, response URL 'https://localhost:4000/authentication/login_callback#state=HRdqLNnA6Eeap23YwiTqZt-RG41BfeeOTf-5cUKyeNA&session_state=f47d2784-6bc6-4e43-9976-6437dfb30b7c&code=5933f67d-201a-4871-b080-78d71610c34a.f47d2784-6bc6-4e43-9976-6437dfb30b7c.a09a64c7-48f7-4ec6-bc15-2fc79b498bff'.
 ---> System.ArgumentNullException: AuthenticationResponse (Parameter 'State')
   at ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect.OpenidConnectPkce.LoginCallBackAsync(String responseUrl)
```
I've had a look at your OpenidConnectPkce class but couldn't see what the issue should be. (Was thinking it might be the casing on the "state" param, but changing it to  "State" instead yielded no positive result. :/
I'm pretty new at blazor, so I can't attach the debugger. But let me know if I can provide any information you might need.

**Comment by chrsin** [comment]
Looking at the code the issue seems to be that the fragment isn't parsed correctly. The first parameter in the fragment will contain a '#'.
A quick test with using this to parse the fragment instead of reading it directly from the Uri in the GetResponseQuery method of the :

```
string fragment = rUri.Fragment;
            if (fragment[0] == '#')
                fragment = fragment.Substring(1);
```

I've created the pull request here: https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/pull/11 that should fix this.

**Comment by Revsgaard** [comment]
Thank you for the bug report. The bug is fixed in commit  https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/commit/71abff2556c3662e81786c5181ecbff107d67007

**Comment by Revsgaard** [comment]
Bug fixet in version 1.5.0 https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/releases/tag/1.5.0

**Comment by chrsin** [comment]
Nice thanks!
