### ISSUE TITLE
Are there any plans to release samples/ documentation for Blazor Server on .net6?

### ISSUE THREAD

**Issue by dan508** [ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect#19]
I'm trying to understand SAML authentication so that I can include it in my Blazor projects. some of these projects are going to be Blazor server, so a sample or documentation would be great. I'll be using a third part IDP, so only the SP side would be required.

**Comment by Revsgaard** [comment]
There are not plans in this component.

You can use the https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2 component in the .NET backend and let .NET handle the session.
