### ISSUE TITLE
Maintain Issuer on Claims

### ISSUE THREAD

**Issue by chrsin** [ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect#20]
It looks like the issuer is lost and just set to the default value of "LOCAL AUTHORITY". 
Looking at the code it might be as simple as adding it to:
https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/blob/e3be3facf7a773e72eb8cc197d55047968c763d1/src/ITfoxtec.Identity.BlazorWA.Oidc/OidcAuthenticationStateProvider.cs#L40

Is there more to it than just adding it there and would that be a change you would accept? :)

**Comment by Revsgaard** [comment]
You are right is was lost, added in the [this](https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/commit/57750fc88254f24d70a07b30eb204a766afd7e8d) commit.

**Comment by chrsin** [comment]
Damn you are fast! :)

Do you have any upcoming release planned?

**Comment by Revsgaard** [comment]
I expect it to be released with the .NET8 update.

**Comment by Revsgaard** [comment]
Released in [1.6.5](https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect/releases/tag/1.6.5)
