### ISSUE TITLE
AuthorizedUris = audience?

### ISSUE THREAD

**Issue by vitalybrandes** [ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect#24]
Is AuthorizedUris actually similar to "audience" in Auth0?

**Comment by Revsgaard** [comment]
No AuthorizedUris is to make it possible for the client to [call APIs on other domains](https://github.com/ITfoxtec/ITfoxtec.Identity.BlazorWebAssembly.OpenidConnect?tab=readme-ov-file#api-calls-to-another-domain).

I think the `ClientId ` is probable equal to `audience` in Auth0
